name: additionalmechanics
main: ru.ardeon.additionalmechanics.AdditionalMechanics
version: 1.0
api-version: 1.13
commands:
    tost:
        description: добавление поля
        usage: /tost <имя>
        permission: additionalmechanics.admin
    horsetest:
        description: test
        usage: /horsetest
        permission: additionalmechanics.admin
    pblock:
        description: добавление блока
        usage: /pblock <имя>
        permission: additionalmechanics.admin
    altar:
        description: добавление altar
        usage: /altar <имя>
        permission: additionalmechanics.admin
    enderbook:
        description: открыть Книггу
        usage: /enderbook
        permission: additionalmechanics.enderbook
    stoptimer:
        description: Запустить таймер рестарта
        usage: /stoptimer <mins>
        permission: additionalmechanics.admin
permissions: #права
    additionalmechanics.admin:
        description: admin access
    additionalmechanics.miner.small:
        description: 1x2
    additionalmechanics.miner.normal:
        description: 3x2
    additionalmechanics.miner.big:
        description: 3x3
    additionalmechanics.miner.extradrop.1:
        description: 11%
    additionalmechanics.miner.extradrop.2:
        description: 22%
    additionalmechanics.miner.extradrop.3:
        description: 33%
    additionalmechanics.miner.extradrop.4:
        description: 44%
    additionalmechanics.miner.radar.power.1:
        description: 3x1
    additionalmechanics.miner.radar.power.2:
        description: 4x2
    additionalmechanics.miner.radar.power.3:
        description: 5x3
    additionalmechanics.miner.radar.coal:
        description: coal
    additionalmechanics.miner.radar.iron:
        description: iron
    additionalmechanics.miner.radar.gold:
        description: gold
    additionalmechanics.miner.radar.lazurit:
        description: lazurit
    additionalmechanics.miner.radar.emerald:
        description: emerald
    additionalmechanics.miner.radar.diamond:
        description: diamond
    additionalmechanics.miner.radar.other:
        description: other
    additionalmechanics.adventurer.radar.power.1:
        description: 4x2
    additionalmechanics.adventurer.radar.power.2:
        description: 5x3
    additionalmechanics.adventurer.radar.power.3:
        description: 6x3
    additionalmechanics.adventurer.horse.hp.1:
        description: none
    additionalmechanics.adventurer.horse.hp.2:
        description: none
    additionalmechanics.adventurer.horse.hp.3:
        description: none
    additionalmechanics.adventurer.horse.hp.4:
        description: none
    additionalmechanics.adventurer.horse.hp.5:
        description: none
    additionalmechanics.adventurer.horse.hp.6:
        description: none
depend: [Multiverse-Core]