name: Additionalmechanics
main: ru.ardeon.additionalmechanics.AdditionalMechanics
version: 1.1
api-version: 1.16
commands:
    tost:
        description: добавление поля
        usage: /tost <имя>
        permission: additionalmechanics.admin
    horsetest:
        description: test
        usage: /horsetest
        permission: additionalmechanics.admin
    pblock:
        description: добавление блока
        usage: /pblock <имя>
        permission: additionalmechanics.admin
    altar:
        description: добавление altar
        usage: /altar <имя>
        permission: additionalmechanics.admin
    enderbook:
        description: открыть Книггу
        usage: /enderbook
        permission: additionalmechanics.enderbook
    stoptimer:
        description: Запустить таймер рестарта
        usage: /stoptimer <mins>
        permission: additionalmechanics.admin
    rideon:
        description: test
        usage: /rideon
        permission: additionalmechanics.admin
    gr:
        description: gradient
        usage: /gr
        permission: additionalmechanics.admin
    launchhook:
        description: test
        usage: /launchhook
        permission: additionalmechanics.admin
    permkit:
        description: test
        usage: /permkit
        permission: additionalmechanics.admin
    registerbuild:
        description: register build
        usage: /registerbuild <x1 y1 z1 x y z name>
        permission: additionalmechanics.admin
    testbuild:
        description: register build
        usage: /testbuild <x1 y1 z1 name>
        permission: additionalmechanics.admin
    trg:
        description: trg
        usage: /trg <region>
        permission: additionalmechanics.admin
    donateadd:
        description: donateadd
        usage: /donateadd <rubs>
        permission: additionalmechanics.admin
    fakeinv:
        description: fakeinv
        usage: /fakeinv
        permission: additionalmechanics.admin
    getvar:
        description: получить переменную игрока
        usage: /getvar <player> <1-5>
        permission: additionalmechanics.admin
    setvar:
        description: задать переменную игрока
        usage: /setvar <player> <1-5> <value>
        permission: additionalmechanics.admin
permissions: #права
    additionalmechanics.admin:
        description: admin access
    additionalmechanics.miner.size.small:
        description: 1x2
    additionalmechanics.miner.size.normal:
        description: 3x2
    additionalmechanics.miner.size.big:
        description: 3x3
    additionalmechanics.miner.extradrop.1:
        description: 11%
    additionalmechanics.miner.extradrop.2:
        description: 22%
    additionalmechanics.miner.extradrop.3:
        description: 33%
    additionalmechanics.miner.extradrop.4:
        description: 44%
    additionalmechanics.miner.radar.small:
        description: 3x1
    additionalmechanics.miner.radar.medium:
        description: 4x2
    additionalmechanics.miner.radar.big:
        description: 5x3
    additionalmechanics.miner.filter.coal:
        description: coal
    additionalmechanics.miner.filter.iron:
        description: iron
    additionalmechanics.miner.filter.gold:
        description: gold
    additionalmechanics.miner.filter.lazurit:
        description: lazurit
    additionalmechanics.miner.filter.emerald:
        description: emerald
    additionalmechanics.miner.filter.diamond:
        description: diamond
    additionalmechanics.miner.filter.other:
        description: other
    additionalmechanics.adventurer.radar.small:
        description: 4x2
    additionalmechanics.adventurer.radar.medium:
        description: 5x3
    additionalmechanics.adventurer.radar.big:
        description: 6x3
    additionalmechanics.adventurer.horse.use:
        description: none
    additionalmechanics.adventurer.horse.hp.1:
        description: none
    additionalmechanics.adventurer.horse.hp.2:
        description: none
    additionalmechanics.adventurer.horse.hp.3:
        description: none
    additionalmechanics.adventurer.horse.hp.4:
        description: none
    additionalmechanics.adventurer.horse.hp.5:
        description: none
    additionalmechanics.adventurer.horse.hp.6:
        description: none
    additionalmechanics.adventurer.horse.speed.1:
        description: none
    additionalmechanics.adventurer.horse.speed.2:
        description: none
    additionalmechanics.adventurer.horse.speed.3:
        description: none
    additionalmechanics.adventurer.horse.speed.4:
        description: none
    additionalmechanics.adventurer.horse.speed.5:
        description: none
    additionalmechanics.adventurer.horse.speed.6:
        description: none
    additionalmechanics.adventurer.horse.speed.7:
        description: none
    additionalmechanics.adventurer.horse.speed.8:
        description: none
    additionalmechanics.adventurer.horse.speed.9:
        description: none
    additionalmechanics.adventurer.horse.speed.10:
        description: none
    additionalmechanics.adventurer.horse.jump.1:
        description: none
    additionalmechanics.adventurer.horse.jump.2:
        description: none
    additionalmechanics.adventurer.horse.jump.3:
        description: none
    additionalmechanics.adventurer.horse.jump.4:
        description: none
    additionalmechanics.adventurer.horse.jump.5:
        description: none
    additionalmechanics.adventurer.horse.jump.6:
        description: none
    additionalmechanics.adventurer.horse.jump.7:
        description: none
    additionalmechanics.adventurer.horse.jump.8:
        description: none
    additionalmechanics.adventurer.horse.jump.9:
        description: none
    additionalmechanics.adventurer.horse.jump.10:
        description: none
    additionalmechanics.adventurer.hook.length.1:
        description: none
    additionalmechanics.adventurer.hook.length.2:
        description: none
    additionalmechanics.adventurer.hook.length.3:
        description: none
depend: [Multiverse-Core]
softdepend: [WorldGuard, PlaceholderAPI, ProtocolLib, LuckPerms]