############################################################
# +------------------------------------------------------+ #
# |                    test                              | #
# +------------------------------------------------------+ #
############################################################
MoonWorldCheck: Wild
world: Wild