name: Additionalmechanics
main: ru.ardeon.additionalmechanics.AdditionalMechanics
version: 1.1
api-version: 1.16

commands:
    adm:
        description: main command
        usage: /adm <subcommand>
        permission: ru.ardeon.additionalmechanics.admin
    horsetest:
        description: test
        usage: /horsetest
        permission: ru.ardeon.additionalmechanics.admin
    altar:
        description: добавление altar
        usage: /altar <имя>
        permission: ru.ardeon.additionalmechanics.admin
    testitemencode:
        description: testitemencode
        usage: /testitemencode
        permission: ru.ardeon.additionalmechanics.admin
    testitemdecode:
        description: testitemdecode
        usage: /testitemdecode
        permission: ru.ardeon.additionalmechanics.admin
    stoptimer:
        description: Запустить таймер рестарта
        usage: /stoptimer <mins>
        permission: ru.ardeon.additionalmechanics.admin
    rideon:
        description: test
        usage: /rideon
        permission: ru.ardeon.additionalmechanics.admin
    gr:
        description: gradient
        usage: /gr
        permission: ru.ardeon.additionalmechanics.admin
    launchhook:
        description: test
        usage: /launchhook
        permission: ru.ardeon.additionalmechanics.admin
    registerbuild:
        description: register build
        usage: /registerbuild <x1 y1 z1 x y z name>
        permission: ru.ardeon.additionalmechanics.admin
    testbuild:
        description: register build
        usage: /testbuild <x1 y1 z1 name>
        permission: ru.ardeon.additionalmechanics.admin
    trg:
        description: trg
        usage: /trg <region>
        permission: ru.ardeon.additionalmechanics.admin
    donateadd:
        description: donateadd
        usage: /donateadd <rubs>
        permission: ru.ardeon.additionalmechanics.admin
    fakeinv:
        description: fakeinv
        usage: /fakeinv
        permission: ru.ardeon.additionalmechanics.admin
    setitemtag:
        description: setitemtag
        usage: /setitemtag "тэг" "значение"
        permission: ru.ardeon.additionalmechanics.admin
    getitemtag:
        description: getitemtag
        usage: /getitemtag "тэг"
        permission: ru.ardeon.additionalmechanics.admin
    prefix:
        description: prefix
        usage: /prefix
        permission: ru.ardeon.additionalmechanics.prefix
    getvar:
        description: получить переменную игрока
        usage: /getvar <player> <1-5>
        permission: ru.ardeon.additionalmechanics.admin
    setvar:
        description: задать переменную игрока
        usage: /setvar <player> <1-5> <value>
        permission: ru.ardeon.additionalmechanics.admin
    addtovar:
        description: задать переменную игрока
        usage: /addtovar <player> <1-5> <value>
        permission: ru.ardeon.additionalmechanics.admin
    addarenastat:
        description: задать переменную игрока
        usage: /addarenastats <player> <1-12> <1-8> <value>
        permission: ru.ardeon.additionalmechanics.admin
    getarenastat:
        description: получить переменную игрока
        usage: /getarenastats <player> <1-12> <1-8>
        permission: ru.ardeon.additionalmechanics.admin
    testgetmeta:
        description: получить переменную игрока
        usage: /testgetmeta <player> <field>
        permission: ru.ardeon.additionalmechanics.admin
    achievementpoints:
        description: манипуляция с очками достижений
        usage: /achievementpoints <get/refresh>
        permission: ru.ardeon.additionalmechanics.admin
    flip:
      description: Бросок монетки
      usage: /flip
    roll:
      description: Случайное число
      usage: /roll
    dice:
      description: Бросок кубика
      usage: /dice
    guild:
      description: guild
      permission: ru.ardeon.additionalmechanics.admin
    giveperm:
      description: guild
      permission: ru.ardeon.additionalmechanics.admin
    moonskip:
      description: moonskip
      permission: ru.ardeon.additionalmechanics.admin
    sidebar:
      description: включение/выключение сайдбара
      permission: ru.ardeon.additionalmechanics.sidebar
    portaladd:
      permission: ru.ardeon.additionalmechanics.admin
    portalmenu:
      permission: ru.ardeon.additionalmechanics.admin
    discordconfirm:
      permission: ru.ardeon.additionalmechanics.discordlink
permissions: #права
    additionalmechanics.admin:
        description: admin access
    additionalmechanics.prefix:
        description: prefix set
    additionalmechanics.miner.size.small:
        description: 1x2
    additionalmechanics.miner.size.normal:
        description: 3x2
    additionalmechanics.miner.size.big:
        description: 3x3
    additionalmechanics.miner.extradrop.1:
        description: 11%
    additionalmechanics.miner.extradrop.2:
        description: 22%
    additionalmechanics.miner.extradrop.3:
        description: 33%
    additionalmechanics.miner.extradrop.4:
        description: 44%
    additionalmechanics.miner.radar.small:
        description: 3x1
    additionalmechanics.miner.radar.medium:
        description: 4x2
    additionalmechanics.miner.radar.big:
        description: 5x3
    additionalmechanics.miner.filter.coal:
        description: coal
    additionalmechanics.miner.filter.iron:
        description: iron
    additionalmechanics.miner.filter.gold:
        description: gold
    additionalmechanics.miner.filter.lazurit:
        description: lazurit
    additionalmechanics.miner.filter.emerald:
        description: emerald
    additionalmechanics.miner.filter.diamond:
        description: diamond
    additionalmechanics.miner.filter.other:
        description: other
    additionalmechanics.adventurer.radar.small:
        description: 4x2
    additionalmechanics.adventurer.radar.medium:
        description: 5x3
    additionalmechanics.adventurer.radar.big:
        description: 6x3
    additionalmechanics.adventurer.horse.use:
        description: none
    additionalmechanics.adventurer.horse.hp.1:
        description: none
    additionalmechanics.adventurer.horse.hp.2:
        description: none
    additionalmechanics.adventurer.horse.hp.3:
        description: none
    additionalmechanics.adventurer.horse.hp.4:
        description: none
    additionalmechanics.adventurer.horse.hp.5:
        description: none
    additionalmechanics.adventurer.horse.hp.6:
        description: none
    additionalmechanics.adventurer.horse.speed.1:
        description: none
    additionalmechanics.adventurer.horse.speed.2:
        description: none
    additionalmechanics.adventurer.horse.speed.3:
        description: none
    additionalmechanics.adventurer.horse.speed.4:
        description: none
    additionalmechanics.adventurer.horse.speed.5:
        description: none
    additionalmechanics.adventurer.horse.speed.6:
        description: none
    additionalmechanics.adventurer.horse.speed.7:
        description: none
    additionalmechanics.adventurer.horse.speed.8:
        description: none
    additionalmechanics.adventurer.horse.speed.9:
        description: none
    additionalmechanics.adventurer.horse.speed.10:
        description: none
    additionalmechanics.adventurer.horse.jump.1:
        description: none
    additionalmechanics.adventurer.horse.jump.2:
        description: none
    additionalmechanics.adventurer.horse.jump.3:
        description: none
    additionalmechanics.adventurer.horse.jump.4:
        description: none
    additionalmechanics.adventurer.horse.jump.5:
        description: none
    additionalmechanics.adventurer.horse.jump.6:
        description: none
    additionalmechanics.adventurer.horse.jump.7:
        description: none
    additionalmechanics.adventurer.horse.jump.8:
        description: none
    additionalmechanics.adventurer.horse.jump.9:
        description: none
    additionalmechanics.adventurer.horse.jump.10:
        description: none
    additionalmechanics.adventurer.hook.length.1:
        description: none
    additionalmechanics.adventurer.hook.length.2:
        description: none
    additionalmechanics.adventurer.hook.length.3:
        description: none
depend: [Multiverse-Core, JDA]
softdepend: [WorldGuard, WorldGuardEvents, PlaceholderAPI, ProtocolLib, LuckPerms, CMI, DeathMessages, DeluxeCombat]