############################################################
# +------------------------------------------------------+ #
# |                    test                              | #
# +------------------------------------------------------+ #
############################################################
guilds:
  adventurers:
    horse:
      hp:
        1: 20
        2: 25
        3: 30
        4: 40
        5: 45
        6: 50
      speed:
        1: 0.2
        2: 0.23
        3: 0.26
        4: 0.29
        5: 0.32
        6: 0.35
        7: 0.38
        8: 0.41
        9: 0.44
        10: 0.47
      jump:
        1: 0.4
        2: 0.45
        3: 0.5
        4: 0.55
        5: 0.6
        6: 0.65
        7: 0.7
        8: 0.75
        9: 0.8
        10: 0.85
    radar:
      small:
        radius: 3
        height: 1
      medium:
        radius: 4
        height: 2
      big:
        radius: 5
        height: 2
  miners:
    radar:
      small:
        radius: 2
        height: 0
      medium:
        radius: 3
        height: 1
      big:
        radius: 4
        height: 2
    